#!/bin/sh

PARENT_DIR=${PARENT_DIR:-$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)}
FIXER_BUILD_ROOT=${FIXER_BUILD_ROOT:-"$PARENT_DIR/dist/build"}
FIXER_TMP_ROOT=${FIXER_TMP_ROOT:-"$FIXER_BUILD_ROOT/tmp"}
FIXER_CARGO_TARGET_DIR=${FIXER_CARGO_TARGET_DIR:-"$FIXER_BUILD_ROOT/cargo-target"}
FIXER_CARGO_HOME=${FIXER_CARGO_HOME:-"$FIXER_BUILD_ROOT/cargo-home"}

: "${TMPDIR:=$FIXER_TMP_ROOT}"
: "${CARGO_TARGET_DIR:=$FIXER_CARGO_TARGET_DIR}"
: "${CARGO_HOME:=$FIXER_CARGO_HOME}"

mkdir -p "$TMPDIR" "$CARGO_TARGET_DIR" "$CARGO_HOME"

export TMPDIR
export CARGO_TARGET_DIR
export CARGO_HOME
